version: '3.8'

services:

  backend:
    build: ./backend
    command: bash -c "alembic -c alembic.ini upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - ./backend/.env
    #environment:
      #- DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    expose:
      - 5432
    # TODO remove these
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ctf_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    
