version: '3.8'

services:

  backend:
    build: ./_build/backend
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./backend:/usr/src/app

    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}

    depends_on:
      - postgres

    networks:
      - back

    


  postgres:
    image: postgres:15.3
    expose:
      - 5432

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - main_db:/var/lib/postgresql/data/

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    networks:
      - back


  adminer:
    image: adminer
    
    depends_on:
      - postgres

    environment:
      ADMINER_DEFAULT_SERVER: postgres

    networks:
      - back

  frontend:
    build: ./_build/frontend

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frontend:/app

    networks:
      - front

    working_dir: /app


  nginx:
    build: 
      context: .
      dockerfile: ./_build/nginx/Dockerfile

    depends_on:
      - frontend
      - backend

    volumes:
      - /etc/localtime:/etc/localtime:ro

    networks:
      - front
      - back


networks:
  front:
  back:

volumes:
  main_db:
